tryingforum/boards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<pk>/', views.board_topics, name='board_topics'),
    path('boards/<pk>/new_topic/', views.new_topic, name='new_topic'),
]

tryingforum/myproject/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('boards.urls')),
]

tryingforum/trialforum/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tryingforum/boards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=255)

    def __str__(self):
        return "{0}{1}".format(self.name,self.description)

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+',on_delete=models.CASCADE)

tryingforum/boards/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Board, Topic, Post
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    brs = Board.objects.all()
    return render(request,'boards/home.html',{'brs':brs})

def board_topics(request, pk):
    br = get_object_or_404(Board, pk=pk)
    return render(request,'boards/topics.html', {'br':br})

def new_topic(request, pk):
    br = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()

        topic = Topic.objects.create(subject=subject,board=br,starter=user)
        post = Post.objects.create(message=message, topic=topic, created_by=user)

        return redirect('board_topics',pk=br.pk)
    return render(request, 'boards/new_topic.html',{'br':br})

tryingforum/templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'boards/css/bootstrap.min.css' %}">

    <title>{% block title %}Fueb Community{% endblock %}</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">FUEB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  <ol class="breadcrumb my-4">
    {% block breadcrumb %}
    {% endblock %}
  </ol>
  {% block content %}
  {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="{% static 'boards/js/bootstrap.min.js' %}"></script>
</body>
</html>

tryingforum/templates/boards/home.html
{% extends 'boards/base.html' %}

{% block title %}
  Fueb Community
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active" aria-current="page">Discussion Boards</li>
{% endblock %}


{% block content %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Products</th>
      <th scope="col">Posts</th>
      <th scope="col">Topics</th>
      <th scope="col">Last Post</th>
    </tr>
  </thead>
  <tbody>
    {% for br in brs %}
    <tr>
      <td>
        <a href="{% url 'board_topics' br.pk %}">{{ br.name }}</a><br>
        <small style="color: #888">{{ br.description }}</small>
      </td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

tryingforum/templates/boards/new_topic.html
{% extends 'boards/base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Discussion Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' br.pk %}">{{ br.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>

{% endblock %}

tryingforum/templates/boards/topics.html
{% extends 'boards/base.html' %}

{% block title %}
  {{ br.name }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'home' %}">Discussion Boards</a></li>
  <li class="breadcrumb-item active">{{ br.name }}</li>
{% endblock %}


{% block content %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in br.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}